# Generated by Django 5.1 on 2024-09-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('phonenumber', models.CharField(db_column='PhoneNumber', max_length=15)),
                ('message', models.CharField(db_column='Message', max_length=255)),
            ],
            options={
                'db_table': 'contactus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('createdon', models.DateField(db_column='CreatedOn')),
                ('customername', models.CharField(db_column='CustomerName', max_length=255)),
                ('description', models.CharField(db_column='Description', max_length=255)),
                ('price', models.CharField(db_column='Price', max_length=255)),
            ],
            options={
                'db_table': 'invoice',
                'managed': False,
            },
        ),
    ]
